export enum VehicleStatus {
  AVAILABLE = 'AVAILABLE',

  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',

  WAITING_MAINTENANCE = 'WAITING_MAINTENANCE',

  OUT_OF_SERVICE = 'OUT_OF_SERVICE',

  DELIVERED_TO_CUSTOMER = 'DELIVERED_TO_CUSTOMER',
}
